title: Jessica Ting
logo: assets/img/profile_circle.png
description: MSc Computational Data Analytics @ GaTech | Economist
theme: jekyll-theme-minimal
color-scheme: light

contact_links:
- label: ðŸ“§ Email
  url: mailto:jessicating.jtjh@gmail.com  
- label: ðŸ’¼ LinkedIn
  url: https://linkedin.com/in/jesstingjh 
- label: ðŸ“„ Resume
  url: assets/resume.pdf  
